### ISSUE TITLE
NEW Bug. CA + EnderIO 1.12.2

### ISSUE THREAD

**Issue by Moobien** [TheIllusiveC4/ConstructsArmory#15] opened 2018-03-07 15:33 UTC
installed the test version of EnderIO and got a crash. Log indicated Conarm as the culprit.

https://gist.github.com/Moobien/8548ebadd4788f3ec82247c10445277d

**Comment by TheIllusiveC4** [comment] 2018-03-07 16:04
Duplicate of [#11](https://github.com/TheIllusiveC4/ConstructsArmory/issues/11)
This has already been fixed. It looks like you're using version 0.0.4-a, the latest version is 0.0.7-a. Please make sure to always update to the latest version before submitting issues to see if the issue has been resolved already.

**Closed as completed** 2018-03-07 16:04 UTC
Labels: duplicate
