### ISSUE TITLE
Incompatibility between Emoticons and ConstructsArmoury. 

### ISSUE THREAD

**Issue by Dust-Finger** [TheIllusiveC4/ConstructsArmory#179] opened 2019-08-20 03:16 UTC
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: conarm-1.12.2-1.2.4
* Tinkers' Construct: TConstruct-1.12.2-2.12.0.157
* Mantle: Mantle-1.12-1.3.3.55
* Forge: 14.23.5.2838
* Emoticons: emoticons-0.3-1.12.2
#### Observed Behavior:
When creating armour with the GUI open in Armoury Forge or when equipping the armour in game, you will receive a crash. The armour texture cannot render in the GUI and you lose the ability to open your inventory if the armour is equipped on the player, as attempting to load the player model from inventory results in the same crash. 

Disabling Emoticons allows the armour to render successfully and gameplay continues as expected, however, the error for the cachekey being null remains, which I have put in the second pastebin link.

I believe the key is being created null initially regardless of whether the value for the key exists or not(somewhere), which might be why when the dynamic texture fails to assign to the cache, it has a null value to pull. 

#### Expected Behavior:
Armour texture is retrieved from cache and renders successfully. 
Cache key is not null when textures are attempted to be loaded from cache.

#### Steps to Reproduce:
A:
    1. Create armour pieces with Constructs. Specifically in my case I had iron core pieces, bronze 
    plates, and iridium trim.
    2. Attempt to create the piece in the armour forge. 
    3. Game crashes.
    4. Disabling the GUI render from config options allows you to create the armour.

B:
    1. If using workaround in A:
       Equipping the created armour will crash the game with the same stack trace, and any further 
       attempts to access your inventory crash the game as it hits the render problem.

C: 
    1. Changing render view to F5 without opening the inventory, but after amour has been 
    equipped the initial time also results in the crash.
...

Crash Log with emoticons [pastebin](https://pastebin.com/ZmSCzCRe).
No crash gameplay w/out Emoticons [pastebin](https://pastebin.com/ezQZRJem)

**Comment by TheIllusiveC4** [comment] 2019-11-03 05:26
Unfortunately, I can't reproduce this issue. Although there is a mod conflict here in that Emoticons is causing the texture models to appear corrupted, that's something that will need to be resolved by the Emoticons developer.

In terms of crashing, it just doesn't crash for me. I've tried both the set of versions that you've listed out and a set of the latest versions of each mod and neither of them crash my game at all.

I've also taken a look at the caching code itself, and I don't really see how the key could be returning null since it passes through a vanilla Minecraft method that should be returning missing textures at worst rather than any null values. My only thought is that maybe Emoticons is disrupting that process somehow, but I can't really tell one way or another since that mod is closed source.

Also, for some reason Emoticons refuses to load in my development environment, so even my ability to properly debug this is somewhat limited anyways.

Due to all these factors, my hands seem a bit tied in regards to this issue so I'm closing this for now until more information comes to light. All I can offer at this juncture is to suggest updating to all of the latest versions and maybe that'll resolve the crashing at least.

**Closed as completed by TheIllusiveC4** 2019-11-03 05:26 UTC
Labels: bug, cannot reproduce, mod conflict, 3rd party issue
