### ISSUE TITLE
Invisible Armors in Server

### ISSUE THREAD

**Issue by Niconoko** [TheIllusiveC4/ConstructsArmory#56] opened 2018-06-07 05:39 UTC
Construct's Armory: v0.0.20B
Tinkers' Construct: v2.10.1.84
Mantle: v1.3.2.24
Forge: 1.12.2-14.23.3.2655

- It would be seen when newly login into a world, but it will be unseen eventually.
- Some of people in the server might not see others wearing armors.
- When armors were unseen, other people will not be able to see any holding items.
- The armors wearer sometime will not be able to see headgear (F5)

**Comment by TheIllusiveC4** [comment] 2018-06-07 13:01
I cannot reproduce this bug, I can see others wearing armor just fine.
- Can you reproduce this with just Construct's Armory and Tinkers' Construct?
- Do you have reliable steps to reproduce this bug?
- Is the armor you're supposed to see not broken? Broken armor will not render.

While an invisible armor bug is within the realm of possibility, I find your third bullet point the strangest. I don't do anything to held item rendering, so my first thought is that this isn't my mod causing this.

**Comment by Niconoko** [comment] 2018-06-08 22:23
I tested with only mods; TC and CA, they're doing fine, but if with some of my mods they turned invisible for some reason, I'll test with the mod in the pack one by one and see what happen.

Here's the mod I got in the pack if you wanna check them out.
![image](https://user-images.githubusercontent.com/24541618/41183505-26a94e14-6ba5-11e8-8b6f-607b0d4a04b4.png)

PS. I updated forge to 2705.

**Comment by TheIllusiveC4** [comment] 2018-06-08 22:39
I notice that you have both TexFix and FoamFix-Anarchy installed so it may be a duplicate of #18 . There's a known issue with that combination of mods and Tinkers' Construct that will cause visual glitches, and this extends to Construct's Armory. Try switching to the Lawful version of FoamFix.

**Comment by Niconoko** [comment] 2018-06-13 06:29
Sorry for the late reply, changing the Foam Fix into Lawful seem to fix the item color that turn white, but the invisible armors still occurring both wearer and the others.

**Comment by TheIllusiveC4** [comment] 2018-06-13 16:59
My only other thought is to try removing Optifine and see if it still occurs, because Optifine is known to cause some rendering issues with certain mods.

**Comment by Niconoko** [comment] 2018-06-14 18:50
Haven't tried with removing optifine yet, but when I put any kind of armor on the forge table to modify something, the armor will turn invisible. I don't know if that could cause from other people doing it near the other players too...?

**Comment by TheIllusiveC4** [comment] 2018-06-14 19:56
It's hard to tell without locating the precise mod causing the issue. Your pack isn't that large, so it shouldn't be too bad. Just keep trimming the mod list by half until you can isolate where the behavior starts happening.

**Comment by Niconoko** [comment] 2018-06-15 07:59
Found it. It's Tex Fix mod that cause armor invisible.
http://minecraft.curseforge.com/projects/texfix

**Comment by TheIllusiveC4** [comment] 2018-06-15 08:22
Oh okay, glad you were able to find out which mod was causing it. I thought that there were only issues with FoamFix-Anarchy installed together with TexFix, but maybe there's more going on. In any case, not my issue for the time being.

**Closed as completed by TheIllusiveC4** 2018-06-15 08:22 UTC
Labels: wontfix, mod conflict
