### ISSUE TITLE
[1.12.2] Armor got invisible after making a new one

### ISSUE THREAD

**Issue by Draskh** [TheIllusiveC4/ConstructsArmory#144] opened 2019-01-26 23:42 UTC
I made a new armor made of Magical Wood, Reinforced Pink Slime Ingot and Refined Obsidian. After taking the armor on they got invisble and I got a bunch of crashes. 

#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 0.2.0   
* Tinkers' Construct: 1.12.2-2.12.0.115  
* Mantle: 1.12-1.3.3.39  
* Forge: 2808
* Optifine: E3
* Industrial Forgoing: 1.12.2-1.12.4-228
* Mekanism: 9.4.11  
* ExtraUtils2: 1.9.8

Crash Log: Please use a paste site like [gist](https://gist.github.com/NickelHub/2840bfeafb8456f7235cf6758b83d193).

**Comment by Draskh** [comment] 2019-01-26 23:51
Here is the log. Don't damn me. It's too big for gist. It's around 200MB unzipped.
[latest.zip](https://github.com/TheIllusiveC4/ConstructsArmory/files/2799617/latest.zip)

**Comment by Draskh** [comment] 2019-01-27 00:02
Here is a screenshot.
![2019-01-27_01 02 05](https://user-images.githubusercontent.com/26455012/51794271-428d1580-21cf-11e9-88f4-b25c8b41eb8e.png)

**Comment by TheIllusiveC4** [comment] 2019-01-27 00:52
Does this also happen without Optifine?

**Comment by Draskh** [comment] 2019-01-27 00:54
After relaunching the game it's visible. It don't seems to crash again.
I will test this more tomorrow.

**Comment by TheIllusiveC4** [comment] 2019-01-27 04:34
Closing this for now. Let me know if it happens again, and if it does then try it without Optifine.

**Closed as completed by TheIllusiveC4** 2019-01-27 04:34 UTC
Labels: mod conflict

**Comment by Draskh** [comment] 2019-01-27 07:06
After relaunching everyhting rendered correctly. Then I disappeared after 15min.

I was not able to reproduce this without Optifine. Should I report it there or won't it be fix though?

Note that this only appears with the new armor I made. The others still rendered as they should without any problem with and without Optifine.
This also happened to my friend playing with me.

**Comment by TheIllusiveC4** [comment] 2019-01-27 10:39
I honestly have no idea what's going on here so I'm not sure how to fix it or that it's even possible on my end. But if you can't reproduce this without Optifine, then it's likely an Optifine compatibility problem. And there's not much I can do there since Optifine is closed source and I have no idea what they're doing to trigger this error. You can try reporting this error to them and see what comes out of it because unfortunately there's not much I can do on my end at this stage.
