### ISSUE TITLE
Metallurgy 4 Reforged - Vulcanite parts freezing the game

### ISSUE THREAD

**Issue by YukiD1st** [TheIllusiveC4/ConstructsArmory#173] opened 2019-06-15 22:09 UTC
#### Versions:
* Construct's Armory: conarm-1.12.2-1.2.4
* Tinkers' Construct: TConstruct-1.12.2-2.12.0.135
* Mantle: Mantle-1.12-1.3.3.55
* Forge: forge-1.12.2-14.23.5.2838
* Conflicting mod: Metallurgy-4-Reforged-0.2.0

#### Observed Behavior:
If I make any armor (chest, helmet, boots or leggins) using a piece of Vulcanite with any TWO other different materials, as soon as you put on the armor that you made, not just the game, but the entire server freezes.

#### Expected Behavior:
The game shouldn't freeze because I combined 3 different materials, since that is what this mod, and Tinkers, is about.

#### Steps to Reproduce: 
1. Make an armor piece using three different materials, one of this materials needs to be Vulcanite.
2. When you complete the armor piece, simply put it on, and the game will freeze.

**Comment by TheIllusiveC4** [comment] 2019-06-16 01:02
Duplicate of https://github.com/TheIllusiveC4/ConstructsArmory/issues/166
This is an issue on Metallurgy 4's end. I believe they have a fix implemented in development already.

**Closed as completed by TheIllusiveC4** 2019-06-16 01:02 UTC
Labels: bug, duplicate, 3rd party issue
