### ISSUE TITLE
Polishing breaks Alien trait

### ISSUE THREAD

**Issue by reserveword** [TheIllusiveC4/ConstructsArmory#254] opened 2020-12-29 17:14 UTC
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.9
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2847
#### Observed Behavior:
When polishing a piece of armor with Alien trait and it is half-grown, the toughness bonus from Alien is gone.
#### Expected Behavior:
Alien trait stacks on top of polishing material for toughness.
#### Steps to Reproduce:
1. Make a Endstone helmet and it have 0 toughness
2. Wait it to grow until it is 1 toughness
3. Polish it with sponge (5 toughness)
4. It should have 6 (5 for sponge + 1 for Alien) toughness now, but it turns out to be 5 toughness
#### Something Maybe Important
1. After polishing the data continues to grow from 5 like 5.01, 5.22, etc.
2. However if the armor is fully grown, the data will not change after polishing, but stops at 5 forever.
3. If you modify the armor, the data is reset to 5.

**Comment by TheIllusiveC4** [comment] 2021-01-20 01:35
Duplicate of https://github.com/TheIllusiveC4/ConstructsArmory/issues/232

As mentioned there, this is a valid issue but not one I plan on addressing since it requires a refactor for how the armor is constructed, which would break current armor implementations. I will keep this in mind for future ports though when I redesign the system.

**Closed as completed by TheIllusiveC4** 2021-01-20 01:35 UTC
Labels: bug
