### ISSUE TITLE
Itemduplication in crafting grid

### ISSUE THREAD

**Issue by TimGoll** [TheIllusiveC4/ConstructsArmory#121] opened 2018-10-05 17:11 UTC
Versions:
forge-1.12.2-14.23.4.2760
conarm-1.12.2-1.1.2

Sometimes you can duplicate armor pieces in the vanilla crafting grid. If you insert the item and remove it, you get a second of this kind. It is not a ghost item. It does not happen every time. This does not happen with other items.

**Comment by TheIllusiveC4** [comment] 2018-10-05 20:39
I cannot reproduce this, no matter how many times I insert armor pieces into the crafting table. Are you able to replicate this with only Construct's Armory and its dependencies installed? Because my first guess is that this is a 3rd party issue that's affecting the crafting process itself.

**Comment by TimGoll** [comment] 2018-10-05 20:41
Hmm, I can try it at a tlater point. I have actually the suspicion that @asiekierka Tinnkered Hegemony is the reason

**Comment by asiekierka** [comment] 2018-10-05 20:42
You forgot to list all of the mods. Next time, list all of the mods.

And yes, of course, TH can cause some odd types of issues due to the way it patches recipes - though it doesn't sound like the kind of issue it could cause...

**Comment by TimGoll** [comment] 2018-10-05 20:44
Hm, it's in a pack. I can post a list, but I think this won't help anybody. I'll try to narrow it down

**Comment by TheIllusiveC4** [comment] 2018-10-19 20:36
@TimGoll Any updates? Were you able to narrow down a mod list?

**Comment by TimGoll** [comment] 2018-10-24 12:12
I have no new information, I had no time to narrow it down. But I can confirm that it happened again. And it happens in all tested crafting tables, including the vanilla table

I have the suspicion it is because of [Lanolin](https://github.com/SirLyle/Lanolin), because it changes CA's items. But it should only add a new nbt value. I have to test it.

**Comment by TimGoll** [comment] 2018-11-11 20:09
Okay, I think I'm on it. I've some news and I have the suspicion that crafttweaker is the reason. I link this issue to them.

**Comment by TheIllusiveC4** [comment] 2018-11-11 23:26
I'm just going to close this issue for the time being because there's too little information to resolve this issue at this juncture and it's uncertain whether the issue stems from Construct's Armory at all. If you get new information that points to this being an issue with Construct's Armory, then I'll be glad to reopen this.

**Closed as completed by TheIllusiveC4** 2018-11-11 23:26 UTC
Labels: needs info, cannot reproduce
