### ISSUE TITLE
Blood Magic Living Armour Crash

### ISSUE THREAD

**Issue by Wanuy** [TheIllusiveC4/ConstructsArmory#75] opened 2018-06-28 01:38 UTC
#### Versions (Be specific, do not write "latest"):
* Construct's Armory:  0.0.21
* Tinkers' Construct: 2.10.1.84
* Mantle: 1.3.2.24
* Forge: 14.23.4.2707
Blood Magic: 2.2.12-97

#### Observed Behavior: 
When a player with Living Armour (doesn't matter the abilities) tries to melee attack someone with a chest plate or helmet from this mod they cannot do any damage to them. Leggings and boots do not give this effect and if worn without a helmet and/or chest plate the player in living armour can do damage. We have tried with different materials and modifiers it does not change this. However, if the player in the Living Armour shoots them with a bow (hits them with an arrow) it crashes the server but not the client

#### Expected Behavior:
Do damage to the player and not crash the server when hit by an arrow

#### Steps to Reproduce:
1. Get a player in Full Living Armour from Blood Magic
2. Get a player in a set of Construct's Armoury Armour (Helmet or Chestplate on their own or in a set
3. Shoot the player in the Construct's armour
4. Crash

Crash Log: https://gist.github.com/Wanuy/9b4e8cf8f173461bbac6af8dd2c65037

**Comment by TheIllusiveC4** [comment] 2018-06-28 01:54
Huh, that sounds very weird from your description. I'll look into it.

**Comment by TheIllusiveC4** [comment] 2018-06-28 08:15
So this is actually caused by something on Blood Magic's end, but I should've been checking for invalid indexes anyways. This will be fixed in the next update.

**Closed as completed** 2018-07-01 03:26 UTC
Labels: bug, code complete
