### ISSUE TITLE
the travellers' bag can copy items inside

### ISSUE THREAD

**Issue by kacho-fuugetsu21** [TheIllusiveC4/ConstructsArmory#229] opened 2020-05-31 21:12 UTC
#### Versions
* Construct's Armory: 1.2.5.9
* Tinkers' Construct:2.13.0.183
* Mantle:1.3.3.55
* Forge:14.23.5.2854
#### Steps to Reproduce:
1. 2 players, an armor with travellers' package and with something inside
2. player 1 put the armor into the armor station and do not do any thing or close the gui
3. player 2 open the armor station gui and change the name of armor, player 1 take away the armor
4. the armor in player 2's gui is still there and when change the name, player 1's gui will be a new armor with same thing inside appear.
the vedio is here, my english is bad so if my report is hard to read, please check it here:
https://www.bilibili.com/video/BV1sV411C7LK

**Comment by TheIllusiveC4** [comment] 2020-05-31 22:47
I'm not entirely sure what's causing this. Logically, there seems to be some sort of desync somewhere with the containers while they're simultaneously open so that it doesn't get removed from all instances when someone crafts with it. Unfortunately, I'm also able to reproduce this with base Tinkers' Construct so this is something that might have to be fixed on their end. Theoretically, I might be able to produce a workaround, but I doubt it since I leverage a lot of the internal Tinkers' stuff and it might do more harm than good to try.

In essence, until I hear otherwise, this seems like a Tinkers' Construct issue and should be reported to those developers since I can reproduce this by replicating tools on the tool tables using the same method. If they produce a fix or can otherwise identify the exact issue, then I can look into replicating that onto Construct's Armory.

**Closed as completed** 2020-06-06 19:09 UTC
Labels: bug, 3rd party issue
