### ISSUE TITLE
High Stride Persists Without Boots Equipped

### ISSUE THREAD

**Issue by Gelles** [TheIllusiveC4/ConstructsArmory#54] opened 2018-06-04 19:33 UTC
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 0.0.20-b
* Tinkers' Construct: 2.10.1.84
* Mantle: 1.3.2.24
* Forge: 14.23.3.2682

#### Observed Behavior:

High Stride (step assist) persists even without High Stride boots equipped or even if the boots are not in the player's inventory.

#### Expected Behavior:

Removing boots removes step assist and resets player's step height

#### Steps to Reproduce:
1. Glue some pistons to a pair of boots for High Stride
2. Put them on. Gain Step Assist!
3. Take them off because you're working in your garden and keep tripping over your fence.
4. Discover that you still have Step Assist without the boots equipped. 

No crash log. Just permanent step assist.

Let me know if you need more information

Edit: Did a quick test: restarting while not wearing the boots resets step height appropriately, so this only occurs for the duration of the session where step height was modified.

**Comment by TheIllusiveC4** [comment] 2018-06-04 20:19
Okay, I was able to reproduce this. Looks like I made the incorrect assumption that the game actively resets the value, but it just initializes the step height when the entity is created and then never writes to it again. This will be fixed in the next update.

**Closed as completed** 2018-06-06 11:03 UTC
Labels: bug, code complete
