### ISSUE TITLE
Modifier Moss and Invisible Ink crash game and server when equiping armor with it

### ISSUE THREAD

**Issue by cooljaz** [TheIllusiveC4/ConstructsArmory#171] opened 2019-06-04 20:02 UTC
Not sure how to format this but using technic mod pack OfficialDracoCraft
and was on a server made for that pack, and I applied to my armor (made of tartarite *Metallurgy*) Moss and Invisible Ink, and the server crashed from what a friend told me as well as my game. Now whenever I join the server crashes and my game crashes.

**Comment by TheIllusiveC4** [comment] 2019-06-04 21:54
Please use the provided template in the future.

Does the game _crash_ or does it _freeze_? There's an important difference. If it _crashes_, then please provide the crash log.

**Comment by cooljaz** [comment] 2019-06-04 22:55
It freezes, and I can't do anything no matter how much I wait. And when I check the crash logs it doesn't show up. As well as the server crashes

**Comment by TheIllusiveC4** [comment] 2019-06-04 23:49
Then it's likely a duplicate of https://github.com/TheIllusiveC4/ConstructsArmory/issues/166
It's a Metallurgy 4 issue.

**Closed as completed by TheIllusiveC4** 2019-06-04 23:49 UTC
Labels: bug, duplicate, 3rd party issue
