### ISSUE TITLE
Armor Disappears

### ISSUE THREAD

**Issue by ReiArsenic** [TheIllusiveC4/ConstructsArmory#30] opened 2018-04-29 07:24 UTC
I have a server and we chose to add this mod. We love the whole concept. We can craft armor, but if you have the crafting table next to tinker's tables, it makes the armor disappear. Thankfully it doesn't consume the materials when it disappeared. What exactly happens is when you click on it, it goes away. If you shift click it goes to your bar, but when you click on it there, it disappears again.

**Comment by TheIllusiveC4** [comment] 2018-04-29 09:45
Sorry, I cannot reproduce this issue. I started a server, placed down all of the Tinkers' Tables with the Crafting Station included, and I'm able to make the armor just fine. No disappearances or anything. Are you able to reproduce this with just Construct's Armory, Tinkers' Construct, and Mantle installed? This could be an issue with another mod interacting with this one.

**Comment by TheIllusiveC4** [comment] 2018-05-10 19:23
Are you still experiencing this issue? I'd like to ask again if you are able to reproduce this with just Construct's Armory, Tinkers' Construct, and Mantle installed? If you're unable to provide this information, I'll have to close this issue.

**Comment by Goldenlion5648** [comment] 2018-05-16 14:45
I had the same issue, but I think I figured out how to reproduce it. First open the armor forge GUI click one of the armor buttons, say the chestplate. Then put the correct materials into the correct slots. If this is done, then the armor will craft correctly. However if the armor materials are put into the correct slots, but the player then closes the GUI and reopens it, the armor will not craft (it "disappears"). A work around is to take out and place back one of the materials. Here is a video to go with my explanation.
[ArmorDisappearing.zip](https://github.com/TheIllusiveC4/ConstructsArmory/files/2009574/ArmorDisappearing.zip)

**Comment by TheIllusiveC4** [comment] 2018-05-16 16:57
Thanks a lot @Goldenlion5648, with that info I was able to reproduce this bug and I'll start working on a solution.

**Closed as completed** 2018-05-17 01:26 UTC
Labels: bug, code complete
