### ISSUE TITLE
[Suggestion] Render glitch with vanilla zombies wearing ConArm armors

### ISSUE THREAD

**Issue by YaibaToKen** [TheIllusiveC4/ConstructsArmory#125] opened 2018-10-14 20:38 UTC
Would it be possible to fix vanilla zombies arms clipping with ConArm armor?

**Comment by TheIllusiveC4** [comment] 2018-10-14 21:27
Duplicate of https://github.com/TheIllusiveC4/ConstructsArmory/issues/99
It's possible, I just haven't gotten to it yet.

**Closed as completed by TheIllusiveC4** 2018-10-14 21:27 UTC
Labels: duplicate
