### ISSUE TITLE
Incompatibility with More Player Models

### ISSUE THREAD

**Issue by Tschipp** [TheIllusiveC4/ConstructsArmory#230] opened 2020-06-06 12:48 UTC
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 1.2.5.8
* Tinkers' Construct: 2.13.0.183
* Mantle: 1.3.3.55
* Forge: 14.23.5.2838
#### Observed Behavior: 
Armor model is not scaled appropriately.
![image](https://user-images.githubusercontent.com/11649893/83944576-c2d07b80-a804-11ea-9b3e-cd7b98883c7d.png)

#### Expected Behavior:
Armor model scales to the bodyparts.
#### Steps to Reproduce:
1. Install MorePlayerModels and apply a (humanoid) model that scales the limbs differently
2. Put on armor

Some more info: I think this should definitely be possible, the mod Extra Bit Manipulation also has custom armor models but scales it to the player. They use render layers instead of traditional armor rendering: https://github.com/Phylogeny/ExtraBitManipulation/blob/1.12.2/src/main/java/com/phylogeny/extrabitmanipulation/armor/LayerChiseledArmor.java

**Comment by TheIllusiveC4** [comment] 2020-06-06 19:08
Duplicate of https://github.com/TheIllusiveC4/ConstructsArmory/issues/187

It seems like this issue also occurs with Botania, Draconic Evolution, and Thaumcraft, which I suspect are using similar rendering methods as I am.

While it certainly may be possible to solve the issue by refactoring the rendering to use a separate layer instead, that seems a bit hackey when the traditional armor layer already exists as a foundation and it doesn't solve the core issue since it seems other mods are also affected by the same problem. From my perspective, the simplest solution would seem to be to contact the More Player Models developer about this issue and see if they can fix the root cause.

**Closed as completed by TheIllusiveC4** 2020-06-06 19:08 UTC
Labels: bug, duplicate

**Comment by Tschipp** [comment] 2020-06-06 21:51
Well, I think it's not entirely the same issue. You mentioned that they all used the vanilla models, but I have another example where the scaling is applied: Mowzie's Mobs:
![image](https://user-images.githubusercontent.com/11649893/83955057-4f079080-a84f-11ea-91af-297906402589.png)
As you can see, the mask is scaled properly.
I'm not quite sure how they do it, but this is their item code: https://github.com/BobMowzie/MowziesMobs/blob/d5afc36191706cb5957fb1f995f36e6f1d1ac52d/src/main/java/com/bobmowzie/mowziesmobs/server/item/ItemBarakoaMask.java
Yes, the problem is widespread. It's been a while since I made custom armor models so I'm not 100% sure of the process, but I think if there was an easy fix on MorePlayerModels' side, he would have probably already done it.

**Comment by TheIllusiveC4** [comment] 2020-06-07 02:45
It seems like the mask is rendered just using the vanilla render layer responsible for rendering non-armor items as equipment, such as when players wear pumpkins, which delegates to the vanilla item renderer. It is curious how this layer scales correctly but the armor layer, under certain circumstances, does not.

> but I think if there was an easy fix on MorePlayerModels' side, he would have probably already done it.

I understand, I'm sure it's not a simple issue. However, I am also in that situation where I would have already implemented a fix if I had discovered one. So far, I have yet to see evidence this is resolvable on my end since I have not seen a mod that implements custom armor models with the vanilla armor renderer that does not also face this compatibility issue.

That said, I'll dig some more into this again and re-open this issue if I discover anything promising. And I'm always open to anyone who has any concrete solutions to offer.

**Comment by Tschipp** [comment] 2020-06-07 10:47
Yes, I will try to get in touch with Noppes and try to get this resolved
