### ISSUE TITLE
revealing modifier w/ thaumcraft

### ISSUE THREAD

**Issue by Tyler81198** [TheIllusiveC4/ConstructsArmory#119] opened 2018-09-23 20:13 UTC
I'd like to be able to add goggles of revealing to my helmet; it could render as a purple visor on the helmet.  it could either use a thaumometer or a pair of goggles of revealing in the armor forge

**Comment by TheIllusiveC4** [comment] 2018-09-23 20:21
Duplicate of https://github.com/TheIllusiveC4/ConstructsArmory/issues/92

**Closed as completed by TheIllusiveC4** 2018-09-23 20:21 UTC
Labels: duplicate
