### ISSUE TITLE
Modern Warfare mod causes Construct's Armory textures to break

### ISSUE THREAD

**Issue by FindingClock4** [TheIllusiveC4/ConstructsArmory#228] opened 2020-05-27 16:31 UTC
![2020-05-27_09 21 29](https://user-images.githubusercontent.com/42501905/83046315-b45fb400-9ffb-11ea-95dc-a90f0bcf9532.png)

Installing MW 2.0 Contagion v0.4.4.6 mc1.12.2 with conarm-1.12.2-1.2.5.9 causes the textures in Construct's Armory to break.
Any ideas?

Mod List:
Construct's Armory 1.2.5.9
JEI Integration 1.6.0
JourneyMap 5.5.2
Just Enough Items 4.15.0.291
Mantle 1.3.3.55
Modern Warfare 2.0 Contagion 0.4.4.6
Optifine HD_U_E3
Tinkers' Construct 2.13.0.183

**Comment by TheIllusiveC4** [comment] 2020-05-27 20:22
Duplicate of https://github.com/TheIllusiveC4/ConstructsArmory/issues/218
Basically, Modern Warfare changes the player model in a way that causes this issue. There's not much I can do on my end as far as I'm aware.

**Closed as completed by TheIllusiveC4** 2020-05-27 20:22 UTC
Labels: bug, duplicate, mod conflict

**Comment by FindingClock4** [comment] 2020-05-27 20:25
thx

**Comment by FindingClock4** [comment] 2020-05-28 05:52
Found a fix using the MorePlayerModels mod to reload the player textures manually.
