### ISSUE TITLE
Armor Helmet

### ISSUE THREAD

**Issue by E-daw** [TheIllusiveC4/ConstructsArmory#25] opened 2018-04-05 00:16 UTC
![2018-04-04_19 14 36](https://user-images.githubusercontent.com/34014927/38341116-9385db70-383c-11e8-8eb3-a3ffab85d120.png)
Maybe it's supposed to be like this but the helmet for the armor clips with your player hat and ends up looking kinda weird.

**Comment by TheIllusiveC4** [comment] 2018-04-05 00:59
This only happens for certain skins that stick out more than the vanilla ones. Incidentally, my own skin does this as well. Not a bug per say, but not intended either. I'll work on a fix for this soon by scaling the armor up a bit.

**Closed as completed** 2018-04-23 04:07 UTC
Labels: weirdness
